resources:
- operator.yaml
- role_binding.yaml
- role.yaml
- service_account.yaml
- priority.yaml
- crds/planetscale.com_vitessclusters.yaml
- crds/planetscale.com_vitesscells.yaml
- crds/planetscale.com_vitesskeyspaces.yaml
- crds/planetscale.com_vitessshards.yaml
- crds/planetscale.com_vitessbackups.yaml
- crds/planetscale.com_vitessbackupstorages.yaml
- crds/planetscale.com_etcdlockservers.yaml
patches:
- path: patchs/vitessclusters_extra_pvcs.patch.json
  target:
    group: apiextensions.k8s.io
    version: v1
    kind: CustomResourceDefinition
    name: vitessclusters.planetscale.com
- path: patchs/vitessshards_extra_pvcs.patch.json
  target:
    group: apiextensions.k8s.io
    version: v1
    kind: CustomResourceDefinition
    name: vitessshards.planetscale.com
- path: patchs/vitesskeyspaces_extra_pvcs.patch.json
  target:
    group: apiextensions.k8s.io
    version: v1
    kind: CustomResourceDefinition
    name: vitesskeyspaces.planetscale.com
images:
- name: planetscale/vitess-operator
  newName: rbouh/vitess-operator
