resources:
- operator.yaml
- role_binding.yaml
- role.yaml
- service_account.yaml
- priority.yaml
- crds/planetscale.com_vitessclusters.yaml
- crds/planetscale.com_vitesscells.yaml
- crds/planetscale.com_vitesskeyspaces.yaml
- crds/planetscale.com_vitessshards.yaml
- crds/planetscale.com_vitessbackups.yaml
- crds/planetscale.com_vitessbackupstorages.yaml
- crds/planetscale.com_etcdlockservers.yaml
patches:
- path: extra_pvcs.patch.json
  target:
    group: apiextensions.k8s.io
    version: v1
    kind: CustomResourceDefinition
    name: vitessclusters.planetscale.com
